# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6ffd95ac22ccbac998952b4d35e5d4d60d8cf968859e817c955bbcbff1c33fa83cabe05a3bb3ffef0e196a1185ff8b8757901b48e3d867c722a49d499e5b5e7

test:
  secret_key_base: b6532d758c391952e5d4ca3246f021b9bedf06ba25c6101b927f2e0ef11dd9c373927ea76dcdde01d9e4537ae5cc3a65220ea4878834adbf9ccffb18cf9fd86a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
